// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxWpmK7AbH1I_mVNgg2Z9A7LeI4sAduM',
    appId: '1:34850021057:web:4380a4520d3a349d157e40',
    messagingSenderId: '34850021057',
    projectId: 'bloodpressure-4828a',
    authDomain: 'bloodpressure-4828a.firebaseapp.com',
    databaseURL: 'https://bloodpressure-4828a-default-rtdb.firebaseio.com',
    storageBucket: 'bloodpressure-4828a.appspot.com',
    measurementId: 'G-FSCN88E37Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5GCwuG6Jae8G38ICpnHLWopPhx9xcS8',
    appId: '1:34850021057:android:bb062d9fca230899157e40',
    messagingSenderId: '34850021057',
    projectId: 'bloodpressure-4828a',
    databaseURL: 'https://bloodpressure-4828a-default-rtdb.firebaseio.com',
    storageBucket: 'bloodpressure-4828a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnreyPXC2o96zvE0coBKTRQzMecNvz04',
    appId: '1:34850021057:ios:1d7253615a7ccb2b157e40',
    messagingSenderId: '34850021057',
    projectId: 'bloodpressure-4828a',
    databaseURL: 'https://bloodpressure-4828a-default-rtdb.firebaseio.com',
    storageBucket: 'bloodpressure-4828a.appspot.com',
    iosClientId: '34850021057-345cm7opgipgbo7b8o5okuh2eh88sq77.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodpressure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTnreyPXC2o96zvE0coBKTRQzMecNvz04',
    appId: '1:34850021057:ios:1d7253615a7ccb2b157e40',
    messagingSenderId: '34850021057',
    projectId: 'bloodpressure-4828a',
    databaseURL: 'https://bloodpressure-4828a-default-rtdb.firebaseio.com',
    storageBucket: 'bloodpressure-4828a.appspot.com',
    iosClientId: '34850021057-345cm7opgipgbo7b8o5okuh2eh88sq77.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodpressure',
  );
}
